### ISSUE TITLE
Extend hash to biblio mappers

### ISSUE THREAD

**Issue by andrew2net** [metanorma/relaton-itu#19]
This is part of the Relaton YAML refactor. https://github.com/metanorma/relaton-bib/issues/7

**Comment by opoudjis** [comment]
Currently this gem and relaton-nist breaks because you have not updated the encoding of roles from metanorma/relaton-bib#6.

This is why it is important to do releases not immediately, but only when the entire stack is synchronised. @CAMOBAP795 is creating scripts for both of us to manage releases in our stacks.

**Comment by andrew2net** [comment]
@opoudjis I don't finish release yet. I updated roles but didn't push it. The sack is synchronized on my local machine.
I don't like to push a lot of commits fixing small issues. Maybe I had to use branches in this case. Merging branches allows squeezing all commits into one.
